---
title: Tratamento de Erros
description: Se der pau nós resolve.
---

## Tratamento de Erros [#error-handling]

Você usa o _tratamento de erros_ para responder às condições de erro que seu programa pode encontrar durante a execução.

Em contraste com os opcionais, que podem usar a presença ou ausência de um valor para comunicar o sucesso ou a falha de uma função, o tratamento de erros permite determinar a causa subjacente da falha e, se necessário, propagar o erro para outra parte do seu programa.

Quando uma função encontra uma condição de erro, ela _lança_ um erro. O chamador dessa função pode então detectar o erro e responder adequadamente.

```swift
func canThrowAnError() throws { // [!code word:throws]
  // Esta função pode ou não lançar um erro
}
```

Uma função indica que pode lançar um erro ao incluir a palavra-chave `throws` em sua declaração. Quando você chama uma função que pode lançar um erro, você antecipa a palavra-chave `try` à expressão.

O Swift propaga automaticamente os erros fora de seu escopo atual até que sejam tratados por uma cláusula de captura.

```swift lineNumbers
do { // [!code word:do:1]
  try canThrowAnError() // [!code word:try] nenhum erro é lançado
} catch { // [!code word:catch]
  // um erro é lançado
}
```

Uma instrução do cria um novo escopo de contenção, o que permite que erros sejam propagados para uma ou mais cláusulas `catch`.

Aqui está um exemplo de como o tratamento de erros pode ser usado para responder a diferentes condições de erro:

```swift lineNumbers
func makeASandwich() throws {
  // ...
}

do {
  try makeASandwich()
  eatASandwich()
} catch SandwichError.outOfCleanDishes { // [!code focus]
  washDishes()
} catch SandwichError.missingIngredients(let ingredients) { // [!code focus]
  buyGroceries(ingredients)
}
```

Neste exemplo, a função `makeASandwich(){:swift}` lançará um erro se não houver pratos limpos disponíveis ou se algum ingrediente estiver faltando. Como `makeASandwich(){:swift}` pode lançar um erro, a chamada de função é envolvida em uma expressão try. Ao envolver a chamada de função em uma instrução do, quaisquer erros lançados serão propagados para as cláusulas `catch` fornecidas.

Se nenhum erro for lançado, a função `eatASandwich(){:swift}` será chamada. Se um erro for lançado e corresponder ao caso `SandwichError.outOfCleanDishes`, a função `washDishes(){:swift}` será chamada. Se um erro for lançado e corresponder ao caso `SandwichError.missingIngredients`, a função `buyGroceries(_:){:swift}` será chamada com o valor `[String]` associado capturado pelo padrão `catch`.

Arremesso, captura e propagação de erros é abordado com mais detalhes no [Tratamento de Erros](../error-handling/index.mdx).
